name: Build Serial Monitor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5 pyserial Pillow
        
    - name: Create icon
      run: python create_icon.py
      
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name "Serial_Monitor" --icon=serial_monitor_icon.ico Serial_Monitor.py
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: Serial_Monitor_Windows
        path: dist/Serial_Monitor.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5 pyserial Pillow
        
    - name: Create icon
      run: python create_icon.py
      
    - name: Build macOS application
      run: |
        pyinstaller --onedir --windowed --name "Serial_Monitor" --icon=serial_monitor_icon.icns Serial_Monitor.py
        
    - name: Create DMG (optional)
      run: |
        brew install create-dmg
        create-dmg \
          --volname "Serial Monitor" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "Serial_Monitor.app" 175 120 \
          --app-drop-link 425 120 \
          "Serial_Monitor.dmg" \
          "dist/"
          
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: Serial_Monitor_macOS
        path: dist/